[package]
name = "trader"
version = "0.1.0"
edition = "2024"

[dependencies]
ibapi = { version = "2.1.0", features = ["async"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = "0.3.31"
time = "0.3.44"
