[package]
name = "trader"
version = "0.1.0"
edition = "2024"

[dependencies]
ibapi = "2.1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = "0.3.31"
time = "0.3.44"
yfinance-rs = "0.7.2"
paft-money = "0.7.1"
iso_currency = "0.5.3"
